version: "3"
services:
  postgres-db:
    image: postgres
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: metabase
      POSTGRES_DB: metabase
      PGDATA: /var/lib/postgresql/data
    volumes:
      # Indique où les données seront situées sur l'hôte: /host/dir:/container/dir
      - ./postgres:/var/lib/postgresql/data
  metabase-app:
    image: metabase/metabase
    restart: always
    container_name: metabase
    ports:
      - 3001:3000
    volumes:
      # Indique où les données seront situées sur l'hôte. /host/dir:/container/dir
      - ./metabase:/metabase-data
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: postgres
      MB_DB_HOST: postgres-db
    depends_on:
      - postgres-db
    links:
      - postgres-db
